### ISSUE TITLE
S3 Origin Protocol Policy must be HTTP

### ISSUE THREAD

**Issue by brannondorsey** [riboseinc/terraform-aws-s3-cloudfront-redirect#2]
https://github.com/riboseinc/terraform-aws-s3-cloudfront-redirect/blob/395cfc72a8e4abb192f6ad3044310851c36696e0/cloudfront.tf#L15

In my experience, and according to [AWS's documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesOriginProtocolPolicy
), the `origin_protocol_policy` must be set to `http-only`. 

> If your origin is an Amazon S3 bucket configured as a website endpoint, you must choose this option. Amazon S3 doesn't support HTTPS connections for website endpoints.

Did you not also find this to be the case? My understanding is that s3 buckets configured as a website can't support HTTPS, so the cloud front distribution must speak HTTP to them when using it as the origin.

Here is my understanding...
`client --HTTPS--> CloudFront --HTTP--> S3 --HTTP--> CloudFront --HTTPS--> client`

Did you not experience this to be a requirement?

**Comment by ronaldtse** [comment]
@brannondorsey you're absolutely correct. This has been fixed in the other repo (https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/) but not here.

Fixed in 4dc9268a16fcfcf178d5e9f34b4b5b0e7890cdee.

Thanks for reporting this!
