### ISSUE TITLE
Doesn't support version 4.2 of the AWS provider

### ISSUE THREAD

**Issue by alexgleith** [riboseinc/terraform-aws-s3-cloudfront-redirect#7]
Version 4.2 of the AWS provider is out, so this module requiring versions 3 is breaking things.

See: https://registry.terraform.io/providers/hashicorp/aws/4.2.0

**Comment by ronaldtse** [comment]
Thanks @alexgleith for letting us know. @phuonghuynh can you please help upgrade this module? Thanks!

**Comment by alexgleith** [comment]
Yeah, I'd like to. Do you have an easy way to test? I'll work on it tomorrow.

**Comment by ronaldtse** [comment]
Thanks @alexgleith for the offer! I'll let @phuonghuynh reply on how to test. From what I know, @phuonghuynh is already working on this issue, but he's finding a way to expose the new [S3 `routing_rule` configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_website_configuration#condition) at the module-level.

**Comment by phuonghuynh** [comment]
> I'll let @phuonghuynh reply on how to test

Committed sample site for testing (simple version), https://github.com/riboseinc/terraform-aws-s3-cloudfront-redirect/tree/master/sample-site

**Comment by phuonghuynh** [comment]
"master" branch now supported for new provider AWS 4x, https://github.com/riboseinc/terraform-aws-s3-cloudfront-redirect/commit/939d8be6ff905f4fb7ee88e1354201b979bd3e5a

**Comment by alexgleith** [comment]
Awesome news, @phuonghuynh! I'll test it now.

**Comment by alexgleith** [comment]
Looks good from my end, thanks heaps!

**Comment by ronaldtse** [comment]
Thank you @phuonghuynh @alexgleith !
