### ISSUE TITLE
Tag version for the last v3 and for the first v4

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-s3-cloudfront-redirect#8]
Similar to https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/issues/42

**Comment by ronaldtse** [comment]
@phuonghuynh please help complete this ASAP, thanks!

**Comment by phuonghuynh** [comment]
Its [done](https://github.com/riboseinc/terraform-aws-s3-cloudfront-redirect/releases/tag/v2.1.0),

**Comment by ronaldtse** [comment]
Thank you @phuonghuynh !
